server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/url?useUnicode=true&useSSL=false&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&allowMultiQueries=true
    username: root
    password: liubei123
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8

logging:
  level:
    com.dbdou.arts.url: debug